import localFont from "next/font/local";
import "../../styles/globals.css"; // Ajuster le chemin si nécessaire

const geistSans = localFont({
  src: "/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Exportez les métadonnées ici
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Fonction de mise en page racine
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
